name: bon_setup_flutter
description: "A personal collection of flutter utilities"
version: 0.3.0
repository: https://github.com/Yoeri-z/bon_setup

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  bon_setup: 0.3.0

  provider: ^6.1.5+1
  go_router: ^17.0.0
  fluttertoast: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
