name: bon_setup
description: A personal collection of dart utilities.
version: 0.3.0
repository: https://github.com/Yoeri-z/bon_setup

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  logger: ^2.6.2
  get_it: ^9.1.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
